### ISSUE TITLE
Typo in floor_base calculus

### ISSUE THREAD

**Issue by Lymkwi** [slemonide/gen#3]
A typo in the name of the `math.floor` function causes crashs when generating.
Error : http://pastebin.ubuntu.com/11025034/
Code : https://github.com/slemonide/gen/blob/master/init.lua#L54
Patch to solve the error : http://pastebin.ubuntu.com/11025056/
Nice mod by the way, keep working like this :+1: .

**Comment by slemonide** [comment]
Fixed that. Thanks.
